name: slendr
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.4.*
  - r-remotes
  - r-reticulate
  - r-checkmate
  - r-cli
  - r-fs
  - r-jsonlite
  - r-lubridate
  - r-magrittr
  - r-rlang
  - r-strex
  - r-stringr
  - r-xml2
  - r-units
  - r-sf
  - r-stars
  - r-rnaturalearth
  - r-rsvg
  - r-magick
  - python>=3.9
  - zlib
  - libtiff
  - libjpeg-turbo
  - bzip2
  - libdeflate
  - liblzma
  - libwebp
  - zstd
  - xorg-libx11
  - fftw
  - pkg-config
  - cmake
  - gcc
  - gxx
  - binutils
